.storybook/decorators.tsx, .storybook/storybook.requires.js, ios/Podfile.lock, lib/atoms/BackButton/BackButton.stories.tsx, lib/atoms/BackButton/BackButton.tsx, package.json, src/App.tsx, yarn.lock
Part of [MOPLAT-543]
<details>
<summary>📦 Published PR as canary version: <code>3.3.0--canary.30.3764849193.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@3.3.0--canary.30.3764849193.0
yarn add @artsy/palette-mobile@3.3.0--canary.30.3764849193.0
```
</details>
[MOPLAT-543]: https://artsyproduct.atlassian.net/browse/MOPLAT-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: back button bg color

.storybook/storybook.requires.js, lib/elements/Input/Input.stories.tsx, lib/elements/Input/Input.tsx, lib/svgs/MagnifyingGlassIcon.tsx, lib/svgs/XCircleIcon.tsx
<details>
<summary>📦 Published PR as canary version: <code>3.4.0--canary.31.3765151739.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@3.4.0--canary.31.3765151739.0
yarn add @artsy/palette-mobile@3.4.0--canary.31.3765151739.0
```
</details>
=> fix: dark mode colors

lib/Theme.tsx, lib/elements/Input/Input.tsx, lib/elements/Tabs/TabBarContainer.tsx, lib/tokens.ts, package.json, yarn.lock
moving from remeda to lodash for consistency 🤔 
<details>
<summary>📦 Published PR as canary version: <code>3.5.1--canary.36.3839055487.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@3.5.1--canary.36.3839055487.0
yarn add @artsy/palette-mobile@3.5.1--canary.36.3839055487.0
```
</details>
=> tools: remeda -> lodash

lib/elements/Skeleton/Skeleton.stories.tsx
tiny fix
<details>
<summary>📦 Published PR as canary version: <code>3.5.2--canary.37.3839766875.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@3.5.2--canary.37.3839766875.0
yarn add @artsy/palette-mobile@3.5.2--canary.37.3839766875.0
```
</details>
=> fix: imports

lib/helpers/text.ts
bringing `apostrophe` and `comma` from eigen
<details>
<summary>📦 Published PR as canary version: <code>5.1.0--canary.44.4077305637.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@5.1.0--canary.44.4077305637.0
yarn add @artsy/palette-mobile@5.1.0--canary.44.4077305637.0
```
</details>
=> feat: add more text things from eigen

lib/elements/Button/Button.tsx, lib/elements/Button/colors.tsx
quick fix
<details>
<summary>📦 Published PR as canary version: <code>8.1.0--canary.52.4135464888.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@8.1.0--canary.52.4135464888.0
yarn add @artsy/palette-mobile@8.1.0--canary.52.4135464888.0
```
</details>
=> fix: Button was missing the restProps

lib/tokens.ts, package.json, yarn.lock
a bit more flexibility
<details>
<summary>📦 Published PR as canary version: <code>8.2.0--canary.53.4145733196.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@8.2.0--canary.53.4145733196.0
yarn add @artsy/palette-mobile@8.2.0--canary.53.4145733196.0
```
</details>
=> feat: typescript magic, allowing negative DS values, and 0 and auto

.storybook/storybook.requires.js, lib/atoms/Box/Box.stories.tsx, lib/atoms/Flex/Flex.tsx, lib/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx, lib/space.stories.tsx, package.json
Flex types were missing the ref, now its fixed.
<details>
<summary>📦 Published PR as canary version: <code>8.3.1--canary.54.4166102610.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@8.3.1--canary.54.4166102610.0
yarn add @artsy/palette-mobile@8.3.1--canary.54.4166102610.0
```
</details>
=> fix: Flex can now have ref without type errors

lib/Theme.tsx, lib/hooks.ts, lib/tokens.ts, src/storybook/decorators.tsx
quick rename of the themes
Some renames:
- `v5light` -> `v3light`
- `v5dark` -> `v3dark`
`v5` was a temporary name, picked to make sure we can try dark mode without messing with v3 (or a potential v4 while we figure stuff out). Now that things are set, we can use `v3` for the non-dark-mode DS, and `v3light` and `v3dark` for v3 with added role name layer (like `background` and `onBackground` etc).
In the future, we will either have a `vX` for a non-dark-mode and `vXlight` and `vXdark`, or if the design team decides to incorporate dark mode, then we will only have a `vXlight` and `vXdark`.
<details>
<summary>📦 Published PR as canary version: <code>8.7.5--canary.59.4179384877.0</code></summary>
<br />
```bash
npm install …
```
=> feat: less confusing name for darkmode support

package.json, scripts/sync-after-change, yarn.lock
As demoed in KS today, this adds a new package.json command `sync-after-change` for publishing changes to [yalc](https://github.com/wclr/yalc). 
Developing shared libraries in a React Native environment is tricky if you need realtime feedback from consuming apps. This is due to the inability to use symlinks or `yarn link`, which is why `yalc` was created. What it does is creates a local mini package manager that one can use to publish to, which consuming apps will then pick up. 
```
$ yarn global add yalc
$ cd palette-mobile
(palette-mobile) $ yalc publish
$ cd eigen 
(eigen) $ yalc add @artsy/palette-mobile
$ cd palette-mobile
(palette-mobile) $ yarn sync-after-change
```
If you've already done this before, all you need to do is run `yarn sync-after-change`.
=> feat(toolchain): Add `yarn sync-after-change` for local dev publishing

lib/elements/Radio/RadioDot.tsx
tests on energy are complaining about this.. strange.
<details>
<summary>📦 Published PR as canary version: <code>10.0.2--canary.66.4203371525.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@10.0.2--canary.66.4203371525.0
yarn add @artsy/palette-mobile@10.0.2--canary.66.4203371525.0
```
</details>
=> fix: removing sc from radiodot

.storybook/storybook.requires.js, lib/Theme.tsx, lib/elements/Button/Button.tests.tsx, lib/elements/Text/LinkText.tsx, lib/elements/Text/Text.stories.tsx, lib/elements/Text/Text.tests.ts, lib/elements/Text/Text.tsx, lib/svgs/Icon.tsx, lib/utils/hooks/useTheme.tsx
text prep for eigen, and provider fix for test error
<details>
<summary>📦 Published PR as canary version: <code>10.0.3--canary.67.4204106221.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@10.0.3--canary.67.4204106221.0
yarn add @artsy/palette-mobile@10.0.3--canary.67.4204106221.0
```
</details>
=> fix: provider error and text prep

src/elements/Button/Button.tsx
Adds hitslop to button props (came across a usecase for specifically the `variant="text"` case of the button where because the boarders werent that clear as in all other variants, it seemed much harder to press the button ([pr](https://github.com/artsy/eigen/pull/8227) that the we fixed that in eigen's button).
This pr is about adding the hitslop on external palette as well.
<details>
<summary>📦 Published PR as canary version: <code>11.0.1--canary.70.4224000496.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@11.0.1--canary.70.4224000496.0
yarn add @artsy/palette-mobile@11.0.1--canary.70.4224000496.0
```
</details>
=> feat: add hitslop on button

src/elements/Screen/Screen.tsx
Adds `noTopSafe` and `noBottomSafe` props to <Screen.Body> component to be able to use only one and not being limited to only use `nosafe`
The reasoning behind this is that we came across an edge case in [eigen](https://github.com/artsy/eigen/blob/main/src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx#L28) where the `nosafe` wasn't working correctly and we changed the inside eigen palette component.
This PR ensures that when moving to use `palette-mobile` we won't break the ui
<details>
<summary>📦 Published PR as canary version: <code>11.0.4--canary.75.4551718796.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@11.0.4--canary.75.4551718796.0
yarn add …
```
=> feat: add noTopSafe noBottomSafe props to screen component

src/elements/EntityHeader/EntityHeader.tsx
while migrating entityheader noticed that it extends SpacerProps that doesn't make sense since all the props that we pass go to Flex. 
<details>
<summary>📦 Published PR as canary version: <code>11.0.7--canary.80.4627106106.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@11.0.7--canary.80.4627106106.0
yarn add @artsy/palette-mobile@11.0.7--canary.80.4627106106.0
```
</details>
=> fix: replace spacerprops with flexprops

package.json
This renames the local palette development script to `yarn local-palette-dev`. Going to also update Eigen to the same so that things are easier to remember. (The underlying script that it points at remains the same, though, to better describe whats happening.)
=> chore(scripts): rename yarn local-palette-dev

README.md
Updates the docs and also republishes a version of palette, as the latest version published to NPM seems to be empty!
=> docs(dev): Update README with notes on yalc

src/elements/Button/Button.tsx
Apparently reanimated doesn't like implicit returns inside the hooks 🤷‍♂️
=> fix: reanimated button crash fix

src/elements/Button/Button.tsx
This is an odd one. After updating the button, noticed this screen appearing in Eigen (only when _not_ debugging; with the debugger on, it doesn't appear): 
The stack trace didn't leave any real info as to where this was coming from but [this pr](https://github.com/artsy/palette-mobile/pull/87/files#diff-ae26129b6f7e71c289c0256844d6aa8039ef2a4c343e09a9e1ecb88a271a853bL272) suggested that it might be coming from Button. 
Running `yarn local-palette-dev` in both repos, I was able to see that after adding "worklet" to two offending spots, the problem went away. 
A natural follow-up here would be to simplify this button a bit and get Moti in for animation. 
=> fix(button): fix worklet crash error in eigen

src/elements/ProgressBar/ProgressBar.tsx
This adds a new `animationDuration` prop so that we can control the behavior in consuming apps. A common flow is:
- Start at 0
- Animate to 100
- Instantly go back to 0 (animationDuration=0)
- Animate to 100
So this gives us that ability. 
=> feat(progress-bar): Add `animationDuration` prop

.storybook/storybook.requires.js, ios/Podfile.lock, package.json, src/elements/Dialog/Dialog.stories.tsx, src/elements/Input/Input.stories.tsx, src/elements/List/List.stories.tsx, src/elements/Message/Message.stories.tsx, src/elements/VisualClue/VisualClue.stories.tsx, yarn.lock
Brought an issue to practice-mobile re: a quick way to reference palette-mobile stories. We ended up mobbing on these updates:
- bump react-native to 0.70.8
- refactor broken imports to accurately reflect current project structure
=> chore: update react native version

Gemfile, Gemfile.lock, package.json
Noticed that in https://github.com/artsy/palette-mobile/pull/91 we also changed a script in `package.json`, this pr fixes that and also updates cocoapods as per [react native migration guide](https://react-native-community.github.io/upgrade-helper/?from=0.70.7&to=0.70.8)
=> build(deps): followup on rn upgrade

src/elements/Button/FollowButton.tsx, src/elements/Button/LinkButton.tsx
Consuming apps (specifically _jest_, in consuming apps) don't like imports that are unspecific, and will lead to strange import behavior. This fixes that in the newly imported button. 
=> fix(import): fix super relative imports

src/elements/ToolTip/ToolTipFlyout.tsx
this is causing a crash in eigen when entering myCollection with a tooltip showing.
before:
https://user-images.githubusercontent.com/49686530/236051985-97273ca9-8daa-4b43-8946-7f8c8d641061.mov
after:
https://user-images.githubusercontent.com/49686530/236051997-2b6c8648-d614-403b-9944-fa163dd43c5b.mov
=> fix: crash in eigen caused by tooltip

.storybook/storybook.requires.js, Gemfile, Gemfile.lock, ios/Podfile.lock, src/elements/ButtonNew/Button.tsx, src/elements/ProgressBar/ProgressBar.tsx, src/elements/Skeleton/Skeleton.tsx
We believe that implicit returns are not playing well with babel resulting in our js functions in hooks not being converted to "worklets" which causes crashes when reanimated tries to run them on the wrong thread. 
https://artsy.slack.com/archives/C02NAJ2CGLW/p1683148878257549
props @gkartalis @damassi for sleuthing
tangential: Adds a couple missed react native upgrade changes, Hermes-engine failing pod install and gem and ruby settings might not be necessary but good to keep in sync. Button story path broke when we brought back old button.
=> fix: no more implicit returns in reanimated hooks

src/elements/Avatar/Avatar.tsx, src/elements/EntityHeader/EntityHeader.tsx
This PR adds support of custom right buttons to the `EntityHeader`. After this PR, we should no longer use the FollowButton and instead use the custom button in the future. It's more scalable and we can use different styles
=> feat: add right button support to entity header

src/elements/Screen/Header.tsx
When we removed the empty flex, there was nothing left to expand the center text area across the way for the left and right elements.
=> fix(header): Make expand

src/elements/Screen/Header.tsx, src/elements/Tabs/TabsContainer.tsx
Addresses [MOPLAT-806] 
Ensures title header is properly centered by introducing widths on the left and right elements. Since these are typically just icons, 50px seems fine for now, but we might need to adjust in the future. 
cc @artsy/mobile-platform 
[MOPLAT-806]: https://artsyproduct.atlassian.net/browse/MOPLAT-806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(tabs): Ensure title content is properly centered 

src/elements/Touchable/Touchable.tsx
This PR resolves [MOPLAT-766](https://artsyproduct.atlassian.net/browse/MOPLAT-766)
Changes `white100` to `transparent` on Touchable `underlayColor` to support dark mode highlight.
|Before|After|
|---|---|
|<video src="https://github.com/artsy/palette-mobile/assets/21178754/f5de8087-9454-40db-8c0b-3d2f3a17fb4a" />|<video src="https://github.com/artsy/palette-mobile/assets/21178754/f7fd9ab8-0650-4c69-b284-7bb398e73330" />| 
|Before|After|
|---|---|
|<video src="https://github.com/artsy/palette-mobile/assets/21178754/e4561fc2-ef16-44f2-aa5d-f45e862c5e8b" />|<video src="https://github.com/artsy/palette-mobile/assets/21178754/bcb8c165-985e-4988-830a-dd71d547881e" />|
|Before|After|
|---|---|
|<video src="https://github.com/artsy/palette-mobile/assets/21178754/7af75915-7323-4077-8c45-77868474b8 …
=> fix(touchable): underlayColor replace white100 to transparent

src/elements/Screen/Header.tsx
Fixes issues where non-animated titles weren't centered properly.
=> fix(screen): fix centering on non-animated title

src/elements/Tabs/TabsContainer.tsx
On android the active tab indicator was not displayed at all, added a conditional check to leave it as it was on iOS and make it visible on android.
|Before|After|
|---|---|
|<img width="382" alt="Screenshot 2023-06-26 at 12 29 36" src="https://github.com/artsy/palette-mobile/assets/21178754/1ed486ff-acf9-42d4-bc65-e329ba6936c5">|<img width="382" alt="Screenshot 2023-06-26 at 12 27 07" src="https://github.com/artsy/palette-mobile/assets/21178754/2d82bee0-d9d6-40e2-89c1-763f895a45c4">|
=> fix: indicator on android is not visible

.storybook/storybook.requires.js, src/elements/EntityHeader/EntityHeader.stories.tsx, src/elements/EntityHeader/EntityHeader.tsx
This PR resolves [CX-3748] 
This PR adds a private icon to the Entity Header when the prop `displayPrivateIcon` is passed
| iOS | Android |
|---|---|
| ![image](https://github.com/artsy/palette-mobile/assets/20655703/72424449-f8da-44d0-a3db-53b39ef11d38) | ![image](https://github.com/artsy/palette-mobile/assets/20655703/d38c8af1-d11e-4951-ba20-f00da9b41024) |
After merging this, a PR will be opened in [Eigen] to add it to the new Artist Collected feature
[CX-3748]: https://artsyproduct.atlassian.net/browse/CX-3748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[Eigen]: https://github.com/artsy/eigen
=> feat(CX-3748): Add private icon to Entity Header

src/elements/Tabs/TabsContainer.tsx
This PR resolves [https://www.notion.so/artsy/Auction-Results-tab-title-breaks-to-two-lines-presumably-this-happened-before-as-well-51597973c1844a8a9c77d7f64ca24b14] 
https://www.notion.so/artsy/Auction-Results-tab-title-breaks-to-two-lines-presumably-this-happened-before-as-well-51597973c1844a8a9c77d7f64ca24b14
Fixes a launch blocking issue that was making bigger tab titles to break into two lines:
iPhone SE screenshots 
|Before|After|
|---|---|
|<img width="411" alt="Screenshot 2023-07-10 at 11 40 08" src="https://github.com/artsy/palette-mobile/assets/21178754/2f64c107-6df3-428f-a9b7-35b584e4a2a7">|![Screenshot 2023-07-10 at 11 23 36](https://github.com/artsy/palette-mobile/assets/21178754/ffbea9dd-f630-4ff9-aa7c-e69f14254e1c)|
=> fix: tab title breaking in smaller phone layouts

src/elements/EntityHeader/EntityHeader.tsx
Adjust the size of `LockIcon` inside `EntityHeader`
Changed the size from 18 to 16
16 is the text size, and 18 is the line height. The icon should be the same size as the text
| before | after |
| --- | --- |
| [screenshots from the previous PR](https://github.com/artsy/palette-mobile/pull/119) | ![simulator_screenshot_D42A4FDF-936D-40E7-8063-D9D671F1702A](https://github.com/artsy/palette-mobile/assets/36167539/34ffcb85-b292-40da-9616-5888fd491aa0) |
=> fix: adjust the size of LockIcon

src/elements/Tabs/TabsContainer.tsx
Resets paddingHorizontal from [inside the library](https://github.com/PedroBern/react-native-collapsible-tab-view/blob/ea2acf3407674cb5ce301ab34d20347a422396ea/src/MaterialTabBar/TabItem.tsx#L94) to prevent text line breaks in smaller components. 
Checked also the rest of the surfaces and nothing breaks.
Screenshots from eigen:
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone SE (3rd generation) - 2023-07-28 at 12 45 38](https://github.com/artsy/palette-mobile/assets/21178754/95778ec8-8fa9-4cc8-aa60-67cd80a6184f)|![Simulator Screenshot - iPhone SE (3rd generation) - 2023-07-28 at 12 45 29](https://github.com/artsy/palette-mobile/assets/21178754/454848d2-71bc-4d5d-8855-c9b3fc2978c9)|
Needed for https://github.com/artsy/eigen/pull/9057
=> fix: reset tab padding style to avoid line breaks

babel.config.js, ios/Podfile.lock, package.json, src/elements/ButtonNew/Button.tsx, src/elements/Pill/Pill.tsx, src/elements/ProgressBar/ProgressBar.tsx, src/elements/Screen/ScreenFlatList.tsx, src/elements/Screen/hooks/useAnimatedHeaderScrolling.tsx, src/elements/Screen/hooks/useListenForScreenScroll.tsx, src/elements/Skeleton/Skeleton.tsx, src/elements/Tabs/SubTabBar.tsx, src/elements/ToolTip/ToolTipFlyout.tsx, yarn.lock
Reverts artsy/palette-mobile#125
will revert the reanimated palette version bump and will go with a canary version till I resolve the issues on the eigen reanimated PR.
So far the only issue seems to be another extremely deprecated package react-native-credit-card-input that was patched from david to use reanimated 1 code.
There is a video there for the behavior of the why this was patched so will go ahead and fix it on Tuesday and then proceed with a palette-mobile release with reanimated 3
=> build(REVERT): bumps palette to reanimated 3

src/elements/Image/Image.stories.tsx, src/elements/Image/Image.tsx
This PR enables prop drilling into the Image element, respecting FastImage props types. Summary of changes:
- If we pass width and width inside style prop, the prior one has priority over
- enables to use more properties from the native element such as resizeMode
I checked the usage in Eigen and we use only [here](https://github.com/artsy/eigen/blob/a717ab184cb495fbee8212bc4c557d3425bce435/src/app/Scenes/Home/Components/HeroUnitsRail.tsx#L41) and [here](https://github.com/artsy/eigen/blob/a717ab184cb495fbee8212bc4c557d3425bce435/src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx#L21), so these changes are not breaking anything, but I haven't checked Folio so far 🤔 
https://github.com/artsy/palette-mobile/assets/15792853/25782721- …
=> feat(Image): enable more styling on the Image element and more

src/elements/Pill/Pill.tsx
MotiPressable was causing an error after the reanimated bump in Eigen.
This PR removes temporarily the animate prop while we investigate it.
more [info](https://artsy.slack.com/archives/C02BAQ5K7/p1690968005585269)
=> fix(Pill): remove animation from MotiPressable

src/elements/Pill/Pill.tsx
Fixes `MotiPressable` animate prop forcing to be executed in the UI thread using `worklet`.
=> fix(Pill): animate moti using worklet

package.json, src/tokens.ts, src/types.ts, src/utils/hooks/useTheme.tsx, src/utils/webTokensToMobile.ts, yarn.lock
This PR bumps `@artsy/palette-tokens` to the latest version and has some unused vars cleanup too(very small stuff).
Tested locally with Eigen and only 1 component is failing there, once the Palette PR is in Place I'll create another PR in Eigen to fix the typings(`MoneyInput.tsx`).
=> chore(palette-tokens): bump palette-tokens to v5

package.json, yarn.lock
Bumps react-native-collapsible-tab-view from 6.1.4 to 6.2.0 in order to be able to start playing around with the Tabs.Masonry in the artwork grids across eigen now that the [MasonryFlashList PR](https://github.com/PedroBern/react-native-collapsible-tab-view/pull/353) got merged and released!
=> feat: add Tabs.Masonry and bump react-native-collapsible-tab-view from 6.1.4 to 6.2.0

.vscode/settings.json, src/elements/ToolTip/ToolTip.tsx
This PR is related to [ONYX-60] 
Adding an `xOffset` prop to `ToolTip` in order to position the tooltip more accurately on an element.
[ONYX-60]: https://artsyproduct.atlassian.net/browse/ONYX-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add xOffset prop to ToolTip

src/elements/ToolTip/ToolTip.tsx
This PR resolves [ONYX-60] 
Add `onPress` prop to `ToolTip` to be able to run code when the user presses/dismisses the tooltip.
[ONYX-60]: https://artsyproduct.atlassian.net/browse/ONYX-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add onPress to ToolTip

src/elements/Tabs/Tabs.stories.tsx, src/elements/Tabs/TabsWithHeader.tsx
Since the title section is just some Views and Text without any interaction we should use pointerEvents `none` in order to have a better UX making the vertical scroll work with the entire content as we see in the video.
https://github.com/artsy/palette-mobile/assets/15792853/10b854b9-dafc-4734-a98a-b509b03282ae
=> feat(Tabs): add pointerEvents none to tabsWithHeader title

src/elements/Tabs/Tabs.stories.tsx, src/elements/Tabs/TabsWithHeader.tsx
The check to not display the title was also affecting `BelowTitleHeaderComponent`, if we don't want to display the large `title` but still want to display `BelowTitleHeaderComponent` we couldn't with the current logic.
The changes here allow us to use `showLargeHeaderText={false}` and still render the `BelowTitleHeaderComponent` if we want.
PS: I checked Eigen and it looks like we never used `showLargeHeaderText={false}` before.
https://github.com/artsy/palette-mobile/assets/15792853/b5d8feb0-0b4a-4dda-8db4-2bedd88a6229
=> feat(TabsWithHeader): show BelowTitleHeaderComponent if we don't display the title

README.md
This PR adds Circle CI status on main. This is useful to quickly access circle ci and check the build status.
=> chore: add build status on circle ci

src/elements/Screen/Header.tsx, src/elements/Screen/ScreenScrollContext.tsx, src/elements/Screen/hooks/useAnimatedHeaderScrolling.tsx, src/elements/Screen/hooks/useListenForScreenScroll.tsx, src/elements/Tabs/hooks/useListenForTabContentScroll.tsx
This PR relates to  [https://artsyproduct.atlassian.net/browse/DIA-105] 
The problem with the tabs is that tabs with big headers lose the scroll functionality to work 100% when the header is fully scrolled.
This PR adds an extra prop to the ScrollContext in order to allow the clients to set up the extra offsets for bigger header contents especially.
https://github.com/artsy/palette-mobile/assets/15792853/aa8e8938-9c5c-46ee-8752-2d077649a945
relates to https://github.com/artsy/eigen/pull/9219
=> feat(tabs): adds scroll offsets to the tabs when checking scroll position

src/elements/Image/Image.tsx, src/utils/createGeminiUrl.ts
There's some discussion going on around the Image and Gemini params([here](https://artsy.slack.com/archives/C05EEBNEF71/p1694436720499889) and [here](https://artsy.slack.com/archives/C02BAQ5K7/p1690277621906139)), while that's not settled I'm exposing the Gemini resize_to param to fix some issues we're having because of the default `resize_to` to `fit`.
=> feat(Image): expose gemini resize mode from Image

src/utils/createGeminiUrl.ts
This PR resolves [ONYX-358]
Co-authored by: @gkartalis 
This addresses some long-standing issues (see threads [here](https://artsy.slack.com/archives/C02BAQ5K7/p1690277621906139) and [here](https://artsy.slack.com/archives/C05EEBNEF71/p1694627963577869?thread_ts=1694436720.499889&cid=C05EEBNEF71)) related to the new `Image` component.
This changes the default behavior of the component, but luckily it's been barely used so far (and is accompanied by an [Eigen PR](https://github.com/artsy/eigen/pull/9263) to change the one usage of it over there).
Prior to this change, there was a mismatch between the [default contain/fit Image (via Gemini) resizing behavior](https://github.com/artsy/palette-mobile/blob/7d66047fd267899b6b2f46fb720b04394eb56b20/src/utils/createGeminiUrl.ts#L11) and the …
=> fix(image): set default Gemini resize mode to `fill`

src/elements/ToolTip/ToolTip.tsx
[Slack Thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1695038296739559)
This PR adds a `flowDirection` prop to `Tooltip` component to force the flow direction. If no flow direction is specified, it will be automatically set (which doesn't seem to work in all cases).
=> fix: Add flowDirection prop to tooltip component

src/elements/Popover/Popover.tsx
This PR resolves [DIA-163] 
This PR addresses an issue where the placement of the popover is broken on Android because of the status bar.
The above solution is inspired by the suggestion in `react-native-popover-view` docs
[DIA-163]: https://artsyproduct.atlassian.net/browse/DIA-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: progressive onboarding positioning on android

src/elements/Pill/Pill.stories.tsx, src/elements/Pill/Pill.tsx
This PR resolves [DIA-110] 
The `artist` variant is not used anywhere and also has been removed from palette web, we're doing the same here plus introducing the `profile` variant to replace it.
https://github.com/artsy/palette-mobile/assets/15792853/e8a9be27-dd45-4913-bbc2-f28f9093c803
[DIA-110]: https://artsyproduct.atlassian.net/browse/DIA-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DIA-110): remove artist variant and replaces with profile on Pill element

src/elements/Message/Message.tsx
This PR removes the unnecessary padding from IconComponent in Message that gets added even there is no X icon shown.
cc @dblandin
=> fix: remove unnecessary padding from IconComponent in Message

src/elements/Pill/Pill.tsx
Small UI correction in the profile variant, horizontal padding should be 1 instead of 2.
=> feat(Pill): adjust horizontal padding of profile variant

src/elements/Pill/Pill.tsx
In Storybook not noticeable, but on Eigen we can see the square, this PR wraps the image with a View doing the masking.
Before:
https://github.com/artsy/palette-mobile/assets/15792853/0f0d712c-3e61-4d2a-afe2-c3418a7f7154
After(Storybook with slow animations feature from Simulator):
https://github.com/artsy/palette-mobile/assets/15792853/d129ebc5-44b4-4bd1-a556-bb75b9cc1733
=> feat(Pill): adjusts the image overflow for profile variant

src/elements/Tabs/TabMasonry.tsx
This PR brings fixes ot my previous PR. It makes the `innerRef` optional in order not to break types. I apologize for missing this
=> fix: make innerRef optional

src/elements/Checkbox/Checkbox.tsx
Exposes `innerAccessibilityProps` to spread accessibility props only in the `View` containing the icons to avoid clashing with the text.
=> feat(checkbox): expose custom accessibilityProps to the View wrapping the icon

android/build.gradle
Fixes the android build duplicate class error by specifying kotlin version.
=> fix: specify compatible kotlin version to avoid dup class error

src/elements/Pill/Pill.tsx
This PR resolves [ONYX-508] 
Fixed vertical centering of text within pills
The text within the pill was not centred. In this PR I set the font weight for the text component to have either the default height of a custom left Icon (18px) or the height of the close icon (15px)
This PR changes only the text within the pill for the pills without the close button and pills with the close button (on the screenshot you can see the changes to lines 1, 2, 4, 5)
| --- | --- |
| ![simulator_screenshot_1BD37656-E881-499C-8901-DC949E469AD2](https://github.com/artsy/palette-mobile/assets/36167539/10ecd849-f20e-4e1b-a0b2-dcc057d4af72) | ![simulator_screenshot_AAD14F12-C54E-4945-B966-A543EC1264DD](https://github.com/artsy/palette-mobile/assets/36167539/2c41828e-c5ab-425f-9cca-7e308a997ee …
=> Fix(ONYX-508): Fix vertical centering of text within pills

src/elements/Pill/Pill.stories.tsx, src/elements/Pill/Pill.tsx
This PR resolves [ONYX-536] 
This ticket comes as an effort to bring in the dotted version of the pill to palette. This change has been approved by the design team and the same component will also be added to Force.
**Not required yet:** Separate selected and disabled states
[ONYX-536]: https://artsyproduct.atlassian.net/browse/ONYX-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: support dotted pill

src/elements/Screen/Screen.stories.tsx, src/elements/Screen/StickySubHeader.tsx, src/elements/Screen/index.tsx
This PR extends the screen component with a sticky sub-header section that collapses. 
**Example:**
https://github.com/artsy/palette-mobile/assets/11945712/a6da238c-3ed6-4a2b-9fcf-7bc47539d1b1
**Updated story:**
https://github.com/artsy/palette-mobile/assets/11945712/86510ca2-eebb-4b1b-968d-46888362f854
=> chore: support animated sticky sub header

src/elements/Screen/StickySubHeader.tsx
This PR makes the following change to the sticky component
- Now the height is dynamic ;) no more custom heights, inject whatever component, and it will adjust dynamically and take that into account during the transition and the height animation
- Support of `subTitle` below the title
https://github.com/artsy/palette-mobile/assets/11945712/67d3ada8-e691-492e-b088-d093b1164697
https://github.com/artsy/palette-mobile/assets/11945712/ecbc53c4-0c96-4ed5-9ae1-920c9ff6ebd4
=> feat: support dynamic height for sticky tabs

ios/PaletteMobile.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, yarn.lock
bump react-native-svg from 13.7.0 to .14.1.0
|Before|After|
|---|---|
|<video src="https://github.com/artsy/palette-mobile/assets/21178754/f8f024f3-c0eb-4114-9987-886794f6368a" width={400} />|<video src="https://github.com/artsy/palette-mobile/assets/21178754/bafe6d2e-b34f-4ad0-ae1e-14455deb7af2" width={400} />|
=> build(deps): bump react-native-svg from 13.7.0 to .14.1.0

src/constants.ts, src/elements/Touchable/Touchable.tsx
This moves our `Touchable` active opacity setting into a constant, and exports a helper to set things globally.
=> feat(constants): Add global opacity setter

src/elements/Tabs/TabsContainer.tsx
Noticed this was out of sync with the rest of our Touchable opacity configurations, so brought it in line.
=> fix(tabs): Ensure tabs use default active opacity

src/elements/Avatar/Avatar.tsx
Adds some polish to the avatar to match images elsewhere in the app, so that when things load it fades in. 
For some reason Moti locked up in a large list (tons of artists in folio), so just went with vanilla reanimated. 
<details>
<summary>📦 Published PR as canary version: <code>13.1.0--canary.180.1173.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@13.1.0--canary.180.1173.0
yarn add @artsy/palette-mobile@13.1.0--canary.180.1173.0
```
</details>
=> feat(avatar): Fade in on load

src/elements/Box/Box.stories.tsx, src/elements/Box/Box.tsx
Paired with @araujobarret on this:
Adds support for `gap`, `columnGap` and `rowGap` in `<Box />`, `<Flex />` now that we upgraded to `rn 72`
https://reactnative.dev/docs/flexbox#row-gap-column-gap-and-gap
|Screenshots||
|---|---|
|![Simulator Screenshot - iPhone 15 - 2024-02-09 at 12 35 59](https://github.com/artsy/palette-mobile/assets/21178754/b17321c1-d774-4659-9be3-48b38a10e4c8)|![Simulator Screenshot - iPhone 15 - 2024-02-09 at 12 36 31](https://github.com/artsy/palette-mobile/assets/21178754/bc86087b-9250-40f4-a7bd-a672deed6958)|
=> feat: support gap columnGap and rowGap in Box, Flex

src/elements/Tabs/TabsWithHeader.tsx
Fixes issue here: https://www.notion.so/artsy/2024-02-09-Folio-App-QA-version-3-0-0-iOS-build-2024-2-9-17-Android-build-234-f6070ceb820a441a8a940ffa201f6d55?p=e28964ca7488480997cc7d4b39dba262&pm=s
=> fix(tabs): Fix padding on large title

src/elements/Button/Button.tsx
This PR resolves [ONYX-760] 
| ------- | ------- |
| <Video src="https://github.com/artsy/palette-mobile/assets/11945712/de3e0c43-a858-44e2-b790-739726bc4aa0" /> |  <Video src="https://github.com/artsy/palette-mobile/assets/11945712/f9143074-9189-4af4-8d30-b4f76b2ad07c" /> |
[ONYX-760]: https://artsyproduct.atlassian.net/browse/ONYX-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: disable width calculation if no long text is specified

src/elements/Screen/Header.tsx, src/elements/Screen/StickySubHeader.tsx
This PR makes some improvements to our screen header components:
- Move as much as possible animations logic to the UI thread
- Fix broken padding on Screen.Header
- Separate Header components to avoid re-renders (Left, Center, Right)
https://github.com/artsy/palette-mobile/assets/11945712/489ae5f7-cd88-4a05-8cdc-ce20f5fcbc53
<details>
<summary>📦 Published PR as canary version: <code>13.1.5--canary.188.1300.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@13.1.5--canary.188.1300.0
yarn add @artsy/palette-mobile@13.1.5--canary.188.1300.0
```
</details>
=> chore: Screen header improvements

src/elements/LazyFlatlist/useHasSeenItem.tsx, src/elements/Screen/StickySubHeader.tsx
This PR fixes a jump on the content when switching between tabs on the activity screen. The behaviour we want to support can not be done with Moti and I had to therefore use reanimated instead
**Before**
https://github.com/artsy/palette-mobile/assets/11945712/565ea78a-58a7-4302-b697-7570f82418b4
**After**
https://github.com/artsy/palette-mobile/assets/11945712/079e5d57-c0cb-4b5e-b312-4ade313acc86
=> fix: content jump after switching tabs

src/elements/Screen/Header.tsx
This PR fixes an issue where the title is not centered if there is no right element provided.
For some reason we specify `hideTitle` and `hideRightElements` as props, which doesn't make much sense to me because I think if you don't want to show an element, simply pass nothing. Anyway, here i am bring this to how it was before my previous changes
**Before**
**After**
https://github.com/artsy/palette-mobile/assets/11945712/96453a65-cb3e-4eb7-ad9f-283104c3eb67
=> fix: title centering when no right element is present

src/elements/Screen/StickySubHeader.tsx
**Sentry error:** https://artsynet.sentry.io/issues/?project=5867225&query=release%3Aandroid-8.33.0-1674645599+error.unhandled%3Atrue&sort=freq&statsPeriod=7d
**Thread:** https://artsy.slack.com/archives/C02BAQ5K7/p1708523668642899?thread_ts=1708517375.346149&cid=C02BAQ5K7
This PR fixes an issue affecting android and leading to break the screen component in Android
https://github.com/artsy/palette-mobile/assets/11945712/7374bad2-1d30-4f24-aeb9-45af73406903
=> fix: opacity animation in android

src/elements/ProgressBar/ProgressBar.tsx
This PR resolves [PHIRE-683] 
Noticed that the progress bar is broken in prod in the onboarding, it was caused due to the rn bump in palette that we did a while ago ([diff here](https://github.com/artsy/palette-mobile/commit/fcf0b32fc8b5faa823da6819080a23d826bb438e#diff-f31c81aceb520986e64c9824ec29a0cbc561fea2fc707996cc1b4a0d4684acf6R30))
The TS error that I tried to fix on the diff above was because useAnimatedStyle expects a return type that is compatible with AnimatedStyleProp<ViewStyle | ImageStyle | TextStyle>. The width property in this case should be a number or a SharedValue<number> instead of a string.
Fixed this by converting the width value to a number before assigning it to the width property in the useAnimatedStyle hook.
This change assumes that the progress prop passed to …
=> fix: progressbar crash in dev and broken in prod

src/elements/Pill/Pill.stories.tsx, src/elements/Pill/Pill.tsx
This PR resolves [PHIRE-118] 
This is a part of a larger initiative for getting rid of the outdated `react-spring` library in eigen. For this reason we need this to get merged to be able to display the onboarding question pills correctly with this pill component that doesn't use react-spring.
from eigen: 
from stories (in palette-mobile):
[PHIRE-118]: https://artsyproduct.atlassian.net/browse/PHIRE-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add onboarding state in pills

.storybook/storybook.requires.js, src/elements/Radio/RadioButton.stories.tsx, src/elements/Radio/RadioButton.tsx
This PR resolves [ONYX-819] 
Radio buttons in palette-mobile currently suffer from poor alignment between button and text. 
Example from SwA flow in Eigen:
It seems to me that people have worked around this problem in Eigen by building up custom flex layouts that include:
- a `<RadioButton />` _without_ the `text` prop
- combined with a custom `<Text />` element
- all of the above wrapped in a `<Touchable />`
(Examples [here](https://github.com/artsy/eigen/blob/7423ddbfa513f79a638193434a118bdc13261d95/src/app/Scenes/Artwork/Components/ArtworkEditionSetItem.tsx#L41-L64) and [here](https://github.com/artsy/eigen/blob/7423ddbfa513f79a638193434a118bdc13261d95/src/app/system/devTools/DevMenu/CodePushOptions.tsx#L81-L89) and [here](https://github.com/artsy/eigen/blob/7423ddbfa513f79a638193434a11 …
=> fix(radio): fix alignment between button and text

src/elements/Collapse/Collapse.tsx, src/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
This PR resolves [ONYX-815] 
- Related Eigen PR: https://github.com/artsy/eigen/pull/9998
This PR adds a `preventUnmount` prop to `CollapsibleMenuItem` that prevents unmounting the content when collapsed. This change is needed in order to not lose the current state when a step in the SWA form is collapsed.
[ONYX-815]: https://artsyproduct.atlassian.net/browse/ONYX-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add `preventUnmount` prop to `CollapsibleMenuItem`

src/elements/Collapse/Collapse.tsx
This PR resolves [APPL-872] 
This PR updates the Collapse element to not render a view when the Collapse is not opened
cc @artsy/onyx-devs 
[APPL-872]: https://artsyproduct.atlassian.net/browse/APPL-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(APPL-872): return null if Collapse is not opened

src/elements/Popover/Popover.tsx
Adds a11y label to the dismiss popover icon.
Reasoning: need to be able to select the dismiss icon on e2e tests
=> feat(a11y): Add accessibility label on popover

ios/Podfile.lock
runs `bundle exec pod install` and adding the missing podfile lock changes after the rn bump
=> fix: rn followups - pod install

package.json
By checking the history of publish jobs noticed a warning that we need to change the `repository` in package json like this to be able to publish.
Usually it was doing the change on the ci and never committing but I committed the change here.
<details>
<summary>📦 Published PR as canary version: <code>13.1.31--canary.220.1879.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@13.1.31--canary.220.1879.0
yarn add @artsy/palette-mobile@13.1.31--canary.220.1879.0
```
</details>
=> build(package.json): fixes package json repo property

src/elements/EntityHeader/EntityHeader.tsx
This updates our entity header with darkmode support, which is necessary for the artwork artist section in private artworks: 
cc @artsy/amber-devs
=> feat(entityheader): add theme support

.all-contributorsrc, CONTRIBUTORS.md
For some reason auto deploys/releases starting failing due to a missing .allcontributorsrc file. I imagine this is due to some kind of auto.rc bump. So to fix i ran `npx all-contributors init` which added the file, and i guess we'll now get a contributor list 🤷
=> fix(ci): Fix missing .allcontributorsrc file for auto.rc

src/elements/EntityHeader/EntityHeader.tsx
Just removes a console.log from EntityHeader :)
=> fix: remove unnecessary console.log from EntityHeader

src/elements/Input/Input.tsx
This PR comes as a follow-up on https://github.com/artsy/eigen/pull/10167
Here we update the Input component to support arrays - this is in order to fix an issue on android where the input placeholder is not being calculated properly.
[sorry the uploaded didn't work on github]
https://artsy.slack.com/archives/C02BAQ5K7/p1714492481009039?thread_ts=1714138172.001059&cid=C02BAQ5K7
=> feat: support placeholders in Input

src/elements/Message/Message.stories.tsx, src/elements/Message/Message.tsx
This PR resolves https://github.com/artsy/eigen/pull/10175#discussion_r1601498539
Add support to `children` in Message Component
=> chore: add support to children in message component

.autorc, .circleci/config.yml
This PR resolves [PHIRE-847] 
Attempt to change auto commits to use artsy shared account. 
Auto according to docs picks up author from package.json: https://intuit.github.io/auto/docs/generated/shipit#examples
I think setting this in the autorc should work but if not we can try to pass explicitly in our auto commands or change the package.json. 
[PHIRE-847]: https://artsyproduct.atlassian.net/browse/PHIRE-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update commit author to shared account #trivial

src/elements/Button/FollowButton.tsx, src/elements/ButtonNew/FollowButton.tsx
This PR resolves [this bug](https://www.notion.so/artsy/Follow-button-in-gallery-list-in-Onboarding-flow-is-broken-f0979e9ec5ba477193b3dd602493f4da?pvs=4) with the follow button that came out of the Sprintly Mobile QA session
=> fix: loading state to FollowButton, hides checkmark when loading

src/elements/Screen/Body.tsx
This PR adds support to disabling keyboard avoidance to `Screen.Body`
**Why am I adding this?**
When the user dismisses a screen where they had the keyboard visible, the `KeyboardAvoidingView` takes action of adjusting the screen content in order to fit it within the screen. Most of the cases, this will result in nothing, since there is nothing to push up, however in the case where we have a sticky button (like the case of SWA landing page "Start Selling" button), we will see that button going down along with the keyboard. Which is something you wouldn't expect since the screen wasn't active.
https://github.com/artsy/palette-mobile/assets/11945712/15372521-dd88-4bc5-8ea0-dd0fb9bec8fb
=> chore: allow disabling keyboard avoidance

src/elements/BackButton/BackButton.tsx
This PR comes as a follow-up on the new SWA flow. The goal here is to support smaller sizes for icons
I am adjusting the size to 18 here and also adding an `iconSize` prop to be able to update it. Luckily, `showX` wasn't used anywhere that's not new
See: https://www.figma.com/design/E6rVm1tiSI4PW3EzibKKZw/Submission-%26-Pre-Consignment-Management?node-id=1061-27259&t=nsaHoKkIDtqvcK0d-0
=> chore: add iconsize prop

src/elements/ProgressBar/ProgressBar.tsx
This PR adds support of injecting styles into the progress bar component. Although ideally we should not inject any styles here, Design wants to be able adjust a few properties of the progress bar when it's not full screen. In the most recent case, making it round
=> chore: support progressBarStyle for ProgressBar component

src/elements/Radio/RadioButton.tsx
This PR comes to support text variants on radio buttons. this is in order to match palette https://www.figma.com/design/gZNkyqLT8AU3T61tluVJyB/Artsy-3.1-Design-System?node-id=6726-3939&m=dev
=> chore: support text variants for radio button

src/elements/Checkbox/Checkbox.tsx
This PR fixes an issue with the styling of the subtitle text. It's currently `black30` but needs to be `black60`.
=> fix: checkbox subtitle text color

src/elements/Input/Input.tsx, src/elements/Input/maskValue.tests.ts, src/elements/Input/maskValue.ts
Add support to masking values for the Input component.
In order to add a mask, you will need to simply provide a string or an array of strings of masks. The mask value should be composed of the digit `9` along with non numeric digits. example: `(999) 9999-999`
https://github.com/artsy/palette-mobile/assets/11945712/363dfb40-ddd3-4c8d-9fb2-a041a4228fc5
=> feat: support masks

src/elements/Input/Input.tsx, src/elements/Input/maskValue.ts
This PR fixes outstanding issues in https://github.com/artsy/eigen/pull/10407 by making the following changes:
- Fix the type of the `onChangeText`
- Allow for `undefined` as a valid initial state
=> fix(Input): proper typing and initial state

.circleci/config.yml
This PR resolves [PHIRE-1021] 
Bumps macos orb vesion to 2.5.1 -> m1
[PHIRE-1021]: https://artsyproduct.atlassian.net/browse/PHIRE-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build(deps-CI): update macOS orb to version 2.5.1

.storybook/storybook.requires.js, src/elements/Button/Button.stories.tsx, src/elements/Button/Button.tsx, src/elements/ButtonNew/Button.stories.tsx
I realised we never moved out to use the ButtonNew(which is neat and has the loading state respecting the variant).
So, this PR brings the stories to the Button we use and uses the property styling given loading state with all variants supported by it.
Before:
https://github.com/artsy/palette-mobile/assets/15792853/e738fbaf-c437-4229-9c08-db96aa29c8ed
After:
https://github.com/artsy/palette-mobile/assets/15792853/c826e479-8109-4e82-acef-5a79a0ff3a07
=> feat(Button): respect variant style given loading state

src/elements/Message/Message.stories.tsx, src/elements/Message/Message.tsx
This PR is related to [DIA-717]
Makes the `title` optional in the `Message` element. We don't have strict rules that the title must be always present, palette web also offers this flexibility, but this PR only enables that.
[DIA-717]: https://artsyproduct.atlassian.net/browse/DIA-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Message): makes title optional

src/elements/Text/Text.tsx
This just sets selectable prop to true by default for Text components. 
Other option is to set to false by default and selectively enable in places we want it, are there places we don't want it?
<details>
<summary>
Before
</summary>
</details>
<details>
<summary>
After
</summary>
</details>
=> feat: add select/copy support to text fields by default

src/elements/Input/Input.tests.tsx, src/elements/Input/Input.tsx
This PR addresses a bug where scrolling was always disabled for input fields, including multiline ones. The result is that none of the multiline inputs in Eigen can display more than 3 lines of text to users.
|-------|-------|
| ![scroll-disabled](https://github.com/user-attachments/assets/4c52091b-4c7d-4386-a06d-5acadec2d546) | ![scroll-enabled](https://github.com/user-attachments/assets/634dc009-6a65-42a8-ba3e-afaa85e8f01a) |
=> fix: multiline input scrolling

src/elements/Tabs/TabFlashList.tsx, src/elements/Tabs/Tabs.ts
Adds flashlist support for Tabs.FlashList
<details>
<summary>📦 Published PR as canary version: <code>13.2.25--canary.247.2306.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@13.2.25--canary.247.2306.0
yarn add @artsy/palette-mobile@13.2.25--canary.247.2306.0
```
</details>
=> feat: add tab.flashlist support

ios/Podfile.lock, package.json, yarn.lock
This PR resolves [PHIRE-1180] 
Bumps `react-native-reanimated` from 3.3.0 to 3.6.3 in order to be able to bump the `react-native` dependency without issues in the future.
Do not merge before we manage to test + bump reanimated in both eigen / energy.
**bonus:** we can get rid of the patch in eigen since it was fixed in `3.4.0`
[PHIRE-1180]: https://artsyproduct.atlassian.net/browse/PHIRE-1180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build(deps): bumps react-native-reanimated from 3.3.0 to 3.6.3

src/elements/Button/Button.stories.tsx, src/elements/Button/Button.tsx, src/elements/Button/FollowButton.tsx, src/elements/Button/colors.ts
Fixes loading states similar to what was done in #243. 
Co-authored by @gkartalis 
https://github.com/user-attachments/assets/40794982-fd80-449f-8a96-517e172cf934
=> refactor(Button): enable loading state for button

ios/Podfile.lock, package.json, src/elements/Screen/ScreenFlatList.tsx, yarn.lock
Bumps reanimated  from 3.3.0 to 3.8.1. Need to test it out before merging, will trigger a canary
<details>
<summary>📦 Published PR as canary version: <code>13.2.33--canary.260.2454.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@13.2.33--canary.260.2454.0
yarn add @artsy/palette-mobile@13.2.33--canary.260.2454.0
```
</details>
=> build(deps): bump reanimated from 3.3.0 to 3.8.1

ios/Podfile.lock, package.json, yarn.lock
Bumps react native from `0.73.9` to `0.73.10` changelog [here](https://github.com/facebook/react-native/releases/tag/v0.73.10)
TLDR; important bug fixes
=> build(deps): bump react-native from 0.73.9 to 0.73.10

src/elements/SearchInput/RoundSearchInput.tsx, src/elements/SearchInput/index.ts, src/svgs/ArrowLeftIcon.tsx
This PR resolves [ONYX-1364] 
This PR adds the new round search input component.
**Figma Designs:**
https://www.figma.com/design/slcFsNpnADoDfhugghOBUI/OtH%3A-Search-%E2%80%93-App?node-id=566-53003&node-type=section&m=dev
___
**How it looks like on Android and iOS:**
https://github.com/user-attachments/assets/45447a55-1c27-43d9-8872-6732f4ba193e
<details>
<summary>📦 Published PR as canary version: <code>14.0.1--canary.278.2756.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@14.0.1--canary.278.2756.0
yarn add @artsy/palette-mobile@14.0.1--canary.278.2756.0
```
</details>
[ONYX-1364]: https://artsyproduct.atlassian.net/browse/ONYX-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add RoundSearchInput component

src/elements/Input/Input.tests.tsx, src/elements/Input/Input.tsx
When trying to log in using the new flow, I noticed some keystrokes not making it. I did some investigation to see why this is happening since I was assuming we are using a non-controlled input for it so performance should not ideal. However, I noticed that:
1. We accidentally brought back the `value` prop [here](https://github.com/artsy/eigen/blob/323d364c69ac26ba67050672cbefaddddad5a075/src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx#L123)
2. The value is being set in Palette Mobile, regardless of using it or not 😮 
Here I am trying my artsy mail mounirdhahri[at]artsymail.com
1. In the video on the left, you can see how it's missing some keystrokes
2. In the video on the right, it's working smoothly (apart from the few mistakes I made 😄 )
| When using a controlled input | …
=> chore: allow using uncontrolled inputs

.eslintrc.js, package.json, src/elements/Avatar/Avatar.tsx, src/elements/ButtonNew/Button.tests.tsx, src/elements/ButtonNew/Button.tsx, src/elements/Dialog/Dialog.tests.tsx, src/elements/Image/Image.tsx, src/elements/Input/Input.tests.tsx, src/elements/Input/Input.tsx, src/elements/Message/Message.tests.tsx, src/elements/Pill/Pill.tests.tsx, src/elements/ProgressBar/ProgressBar.tsx, src/elements/Screen/hooks/useAnimatedHeaderScrolling.tsx, src/elements/Screen/hooks/useListenForScreenScroll.tsx, src/elements/Skeleton/Skeleton.tsx, src/elements/ToolTip/ToolTip.tests.tsx, src/elements/ToolTip/ToolTipFlyout.tsx, src/setupJest.ts, yarn.lock
This PR resolves [PHIRE-1347] 
After upgrading reanimated we noticed a bunch of new warnings coming up.
They pointed to a missuse of `useSharedValue`, as seen [here](https://docs.swmansion.com/react-native-reanimated/docs/core/useSharedValue/#react-compiler-support) we need to avoid accessing the `.value` directly and also mutating values directly `.value = "whatever"`.
Instead we should use the getters and setters as pointed in the PR below.
Nothing changes in the functionality of the animations.
Some other bonus stuff:
properly enabled the `eslint-plugin-testing-library` that wasn't working properly before, and fixed some test issues.
[PHIRE-1347]: https://artsyproduct.atlassian.net/browse/PHIRE-1347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> refactor: proper use of useSharedValue

src/elements/SearchInput/RoundSearchInput.tsx
This PR increases the `hitslop` of the `RoundSearchIcon` to make it easier to tap.
|--------|--------|
| <img src="https://github.com/user-attachments/assets/7b3fda79-f18f-45e8-a39d-02a0d9b21133" /> | <img src="https://github.com/user-attachments/assets/138f4d54-cf3d-4aa2-b1ee-6febfcaf1a91" /> |
=> chore: increase hitslop of search icon

src/elements/Button/Button.tsx
I am adding a test ID to the spinner that is displayed in a button when the `loading` prop is set to true so that React Native Testing Library test in Eigen can make assertions about it.
=> feat: add button loading spinner testid

src/elements/VisualClue/VisualClue.stories.tsx, src/elements/VisualClue/VisualClueDot.tsx, yarn.lock
> [!NOTE]
>
> This depends on the updated tokens from https://github.com/artsy/palette/pull/1415
This PR resolves [ONYX-1463] 
In order to run an experiment with visual indicator colors, we need to be able pass in a custom color to the `VisualClue` component
The accompanying story now documents the customizable colors and (already) customizable diameters for this component:
[ONYX-1463]: https://artsyproduct.atlassian.net/browse/ONYX-1463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: allow VisualClue color to be customized

src/elements/Message/Message.stories.tsx, src/elements/Message/Message.tests.tsx, src/elements/Message/Message.tsx
This PR resolves [ONYX-1459] 
As per design, add a new icon position to the message component - bottom
In addition, add dark message variant
<image src="https://github.com/user-attachments/assets/b9b5d90c-2951-4107-b3e5-f4dcfd88308d" width="250" />
[ONYX-1459]: https://artsyproduct.atlassian.net/browse/ONYX-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ONYX-1459): add bottom icon position and dark variant to message component 

src/elements/Pill/Pill.stories.tsx, src/elements/Pill/Pill.tsx
This PR resolves [ONYX-1482] 
This PR adds a new variant called `link` to the Pill component.
Link to the conversation over Figma: https://www.figma.com/design/Z9legdjhKORHt0vOGpvBg3?node-id=268-49788&m=dev#1087158211
[ONYX-1482]: https://artsyproduct.atlassian.net/browse/ONYX-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add link pill variant

src/elements/EntityHeader/EntityHeader.tsx
This PR resolves [PBRW-435] 
Fixes an issue with ellipsizeMode on android (another related PR [here](https://github.com/artsy/eigen/pull/11047))
|Before|After|
|---|---|
|![Screenshot_1738930566](https://github.com/user-attachments/assets/2e9f2896-ac5f-48cc-b0ad-30690685c533)|![Screenshot_1738930543](https://github.com/user-attachments/assets/97c4ebb6-9d64-4410-a422-66f26497a848)|
|Before|After|
|---|---|
|![Simulator Screenshot - iPhone 16 Pro - 2025-02-07 at 13 27 18](https://github.com/user-attachments/assets/2c033e6d-cdb1-4882-a3c8-ec5e83a0fc3f)|![Simulator Screenshot - iPhone 16 Pro - 2025-02-07 at 13 27 21](https://github.com/user-attachments/assets/89a6d44e-ad3c-4983-8698-85fb03ea720a)|
[PBRW-435]: https://artsyproduct.atlassian.net/browse/PBRW-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
=> fix: entity header ellipsizeMode

README.md
This comes out of this Slack discussion, which notes that the home view docs in Notion are not the most easily discoverable.
Trying to improve that here by linking out from the palette docs, per @oxaudo's suggestion.
=> docs(home view): add a link to Notion docs

src/elements/Input/Input.tsx, src/elements/Input/helpers.ts
This PR fixes the input component dark mode issues on Folio.
**What changes does this PR do?**
Instead of setting input color and border as hard coded values, this PR makes them dynamic. That's it
<details>
<summary>📦 Published PR as canary version: <code>14.0.23--canary.305.3162.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@14.0.23--canary.305.3162.0
yarn add @artsy/palette-mobile@14.0.23--canary.305.3162.0
```
</details>
=> fix: dark-mode for inputs

src/elements/Input/helpers.ts
This PR resolves https://artsy.slack.com/archives/C02BAQ5K7/p1739444115801439
Fix the default color for inputs.
=> fix: default color for inputs

src/elements/Popover/Popover.tsx
This PR fixes an issue with dark mode on popover menu in app.
|--------|--------|
| <img src="https://github.com/user-attachments/assets/bbc2349c-0fe1-4cd1-b2bb-cb79197d2afc" /> | <img src="https://github.com/user-attachments/assets/31dbe780-7c18-4ff3-b561-bdb9ce7f1935" /> |
=> fix: popovers on dark mode

src/elements/Touchable/Touchable.tsx
This PR resolves [ONYX-1517] 
* Related PR: https://github.com/artsy/eigen/pull/11499
While replacing touchable components with the new [RouterLink](https://github.com/artsy/eigen/blob/a1b585ff4a84ac87ff474959c050cf338e63985c/src/app/system/navigation/RouterLink.tsx#L24), I discovered that Palette's `Touchable` component (which isn't widely used in the app) only works in some cases.
This PR replaces [TouchableHighlight](https://reactnative.dev/docs/touchablehighlight) with [TouchableOpacity](https://reactnative.dev/docs/touchableopacity) in the `Touchable` component. The difference is marginal, but `TouchableHighlight` does not work with images (see videos).
Use Palette's `Touchable` component in Eigen's `RouterLink`. 
**Before:**
Images aren't responding to touch. …
=> fix: Replace TouchableHighlight with TouchableOpacity in Touchable

src/elements/Screen/Screen.stories.tsx, src/elements/Screen/StickySubHeader.tsx
This PR resolves [ONYX-1606] 
Add largeTitle prop to StickySubHeader
https://artsy.slack.com/archives/C05EQL4R5N0/p1742206684262199
| iOS | Android |
| --- | --- |
| <img width="352" alt="image" src="https://github.com/user-attachments/assets/e9bf01b7-e52b-4d21-9a65-8dc120169569" />  | <img width="352" alt="image" src="https://github.com/user-attachments/assets/d7762297-9139-46e0-bd02-9695c1f74f8d" /> |
[ONYX-1606]: https://artsyproduct.atlassian.net/browse/ONYX-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ONYX-1606): add largeTitle prop to StickySubHeader

ios/Podfile.lock, package.json, yarn.lock
Bumps the flashlist dep to latest
<details>
<summary>📦 Published PR as canary version: <code>14.0.33--canary.317.3340.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@14.0.33--canary.317.3340.0
yarn add @artsy/palette-mobile@14.0.33--canary.317.3340.0
```
</details>
=> build(deps): bump flashlist to latest

src/elements/Skeleton/Skeleton.tsx
This PR resolves [PBRW-395] 
Removes text from android skeletons 
|Before|After|
|---|---|
|<video src="https://github.com/user-attachments/assets/a0c8136d-0990-4eb2-b37d-ab88fad2a6a1" width="300" />|<video src="https://github.com/user-attachments/assets/ce428e00-92e1-4c50-96c3-e41acc61f336" width="300" />|
Stories:
|Before|After|
|---|---|
|<video src="https://github.com/user-attachments/assets/dc945081-f886-4037-9235-931a23a47df7" width="300" />|<video src="https://github.com/user-attachments/assets/d390a70d-f010-4776-85cb-79f5e5f2444d" width="300" />|
|Before|After|
|---|---|
|<video src="https://github.com/user-attachments/assets/a15d2ff1-0d20-4ac2-80c6-083b6d92bf18" width="300" />|<video src="https://github.com/user-attachments/assets/a15d2ff1-0d20-4ac2-80c6-083b6d92bf18" width="300" …
=> fix: remove skeleton text on android devices

src/elements/Screen/Header.tsx, src/elements/Screen/ScreenScrollContext.tsx, src/elements/Screen/StickySubHeader.tsx, src/elements/Screen/hooks/useListenForScreenScroll.tsx, src/elements/Screen/hooks/useShowLargeTitle.ts
This PR resolves [ONYX-1652] 
This PR brings some improvements and fixes to our scroll view wrapper. 
- We used to have an issue with the screen bouncing when you scroll up on
https://www.notion.so/artsy/Scrolling-up-isn-t-smooth-and-the-content-stutters-iOS-1c7cab0764a08019946dff1be06a775f
- Performance wasn't stable - we were using react state instead of reanimated
https://github.com/user-attachments/assets/a4eb4a9d-12fe-40a0-b40b-7361056c575a
[ONYX-1652]: https://artsyproduct.atlassian.net/browse/ONYX-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
<details>
<summary>📦 Published PR as canary version: <code>14.0.41--canary.327.3490.0</code></summary>
<br />
```bash
npm install …
```
=> feat: improve scroll and performance on Screen.Flatlist

src/tokens.ts
Resolves [Notion-Several-cases-of...](https://www.notion.so/artsy/Several-cases-of-type-that-has-low-bg-contrast-and-that-likely-don-t-meet-accessibility-guidelines-1a1cab0764a0808c97c6e5894678a40e?pvs=4) 
* Related Eigen PR: https://github.com/artsy/eigen/pull/11851
This increases dark mode `onBackgroundMedium` color to increase text contrast (black30 -> black60).
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-04-07 at 13 02 47](https://github.com/user-attachments/assets/b70e4cc7-fd57-4104-85f9-55dff57f81ee) | ![Simulator Screenshot - iPhone 16 - 2025-04-07 at 13 04 33](https://github.com/user-attachments/assets/2f5d02b3-c9f4-4762-bb24-555717700e26)|
=> fix: Increase dark mode onBackgroundMedium to increase contrast

src/tokens.ts
Increase `onBackgroundMedium` dark theme color for the app. This will increase the contrast for tab title color for non-active tabs.
| --- | --- |
| ![Simulator Screenshot - iPhone 16 - 2025-04-14 at 11 34 57](https://github.com/user-attachments/assets/d1313dc9-cd5a-4da2-baed-b0ebae93191b)|![Simulator Screenshot - iPhone 16 - 2025-04-14 at 11 35 40](https://github.com/user-attachments/assets/3cb61c57-059a-449b-94f0-22cf58af5872) |
=> fix: Increase contrast for onBackgroundMedium dark theme color

.autorc
This PR attempts to fix an issue where we had a double release in the previous PR (#332)
I believe the double release happened because we have duplicate plugins for releasing in [.autorc](https://github.com/artsy/palette-mobile/blob/main/.autorc#L4) and in [@artsy/auto-config](https://github.com/artsy/auto-config/blob/main/package.json#L51), which called the commands to release twice, causing the double release issue
This is an attempt to fix it
=> chore: remove duplicate auto-release plugins

src/svgs/ChevronIcon.tsx
This PR resolves [ONYX-1693] 
This PR fixes an issue with the chevron icon.
The implementation of the chevron icon was using wrong icons, instead of using separate svgs, we were using the arrow icon svgs. The latters are thinner and wider.
**Before**
**After**
[ONYX-1693]: https://artsyproduct.atlassian.net/browse/ONYX-1693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: chevron icon component

src/elements/Message/Message.tsx
This PR resolves [ONYX-1694] 
The background of the info message seems to be too light (blue10) in dark mode, and the title contrast ratio isn’t good enough. We need to make the title a bit lighter and the background darker.
This PR aligns the text color with other message variants (using `blue150` instead of `blue100` for a higher contrast ratio).
**Message Components:**
| --- | --- |
|![Simulator Screenshot - iPhone 16 - 2025-04-24 at 10 20 54](https://github.com/user-attachments/assets/559408c9-b51d-464a-8be6-b29021f6c8f9) |![Simulator Screenshot - iPhone 16 - 2025-04-24 at 10 20 43](https://github.com/user-attachments/assets/f2666aa1-577b-4fb0-8d53-d2998459a75e) |
| --- | --- |
**Contrast Ratio (after):**
| Dark | Light |
| --- | --- |
|<img …
=> fix: Info message component contrast ratio

src/elements/Pill/Pill.tsx
Follow up for https://github.com/artsy/palette-mobile/pull/337 & [ ](https://github.com/artsy/eigen/pull/11985)
Set Pill selected text color to theme-independent white.
=> fix: Set Pill selected text color to theme-independent white

src/elements/Tabs/TabsContainer.tsx
This PR resolves [ONYX-1676] 
This PR adds support of:
- Pills instead of tabs inside Tabs.
```typescript
<Tabs
renderHeader={MyCollectionCollectorProfileHeader}
onTabPress={(tab) => {
setActiveNavigationTab(tab as MyCollectionNavigationTab)
}}
...
usePills // 👈👈👈 new prop
>
```
- Using a sticky button to the right of the pills
```typescript
<Tabs
renderHeader={MyCollectionCollectorProfileHeader}
headerHeight={500}
pagerProps={{
scrollEnabled: false,
}}
onTabPress={(tab) => {
setActiveNavigationTab(tab as MyCollectionNavigationTab)
}}
usePills
stickyTabBarComponent={ // 👈👈👈 new prop
<Flex flexDirection="row" alignItems="center" gap={1} pr={2}>
<Touchable hitSlop={ICON_HIT_SLOP} onPress={() => {}}>
<FilterIcon height={DEFAULT_ICON_SIZE} width={DEFAULT_ICON_SIZE} />
</Touchable>
<Touchable …
```
=> feat: support pill tabs

src/elements/Screen/StickySubHeader.tsx
This PR resolves https://www.figma.com/design/Z9legdjhKORHt0vOGpvBg3/App%E2%80%A8IA-and-Shortcuts?node-id=3132-64319&p=f&m=dev
This PR increases the bottom margin below the sticky header title.
=> chore: increase spacing below subtitle title

src/elements/SearchInput/RoundSearchInput.tsx
This PR fixes accessibility issues on the search input at the different text sizes.
Here I tested not just 2x, but also 3x and 1.5x and 1x 
**Before**
**After**
=> fix: accessibility issues on search input

src/tokens.ts
This PR removes palette figma link from our docs.
**Context:** https://artsy.slack.com/archives/CHVFQ06DV/p1745918628979609
=> chore: remove figma link from palette

src/elements/Tabs/TabsContainer.tsx
This PR resolves https://www.notion.so/artsy/Tabs-changing-weirdly-1ebcab0764a080ab87acdc8ffe6f4649?pvs=4
This PR increases the debounce focused tab duration to make sure that we don't show the tab transition.
https://github.com/user-attachments/assets/466793bf-f629-44c1-ae1e-68db53390258
=> chore: increase debounce focued tab duration

.eslintrc.js, package.json, src/elements/BackButton/BackButton.tsx, src/elements/Banner/Banner.tsx, src/elements/Button/Button.tsx, src/elements/Button/LinkButton.tsx, src/elements/ButtonNew/Button.tsx, src/elements/ButtonNew/LinkButton.tsx, src/elements/Checkbox/Checkbox.tsx, src/elements/Chip/Chip.tsx, src/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx, src/elements/Dialog/Dialog.tsx, src/elements/Input/Input.tests.tsx, src/elements/Input/Input.tsx, src/elements/LegacyScreen/LegacyScreen.tsx, src/elements/LegacyTabs/StepTabs.tsx, src/elements/LegacyTabs/Tab.tsx, src/elements/MenuItem/MenuItem.tsx, src/elements/Message/Message.tsx, src/elements/Radio/RadioButton.tsx, src/elements/Screen/Header.tsx, src/elements/SearchInput/RoundSearchInput.tsx, src/elements/ToolTip/ToolTipFlyout.tsx, src/elements/Touchable/Touchable.stories.tsx, yarn.lock
This PR resolves [PHIRE-1774] 
Introduces `plugin:react-native-a11y/basic` for linting when it comes to basic accessibility.
Mostly adds Roles and Labels here and there on Touchables.
[PHIRE-1774]: https://artsyproduct.atlassian.net/browse/PHIRE-1774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add accessibility roles and labels to various components for improved a11y

src/elements/Checkbox/Checkbox.tsx, src/elements/Radio/RadioButton.tsx, src/elements/Text/LinkText.tsx
This PR resolves [PHIRE-1813] 
improves accessibility of radiobutton checkbox and Linktext - I will follow up with an eigen pr to make both work with no issues since I deprecated the problematic `checkboxAccessibilityProps` that weren't properly used and passed
[PHIRE-1813]: https://artsyproduct.atlassian.net/browse/PHIRE-1813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(a11y): improve checkbox, radiobutton, linkText a11y

src/elements/Checkbox/Checkbox.tsx
This PR resolves [PBRW-814] 
Reverts making checkbox pressable -> back to it being `TouchableWithoutFeedback`
see videos below.
|Before|After|
|---|---|
|<video src="https://github.com/user-attachments/assets/b863d142-bbcd-4925-989f-1cb146133d3a" width="300" />|<video src="https://github.com/user-attachments/assets/71e303e1-c4bf-4f82-b88e-6e94d3b21743" width="300" />|
[PBRW-814]: https://artsyproduct.atlassian.net/browse/PBRW-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: checkbox issue with children

src/elements/Tabs/TabsContainer.tsx
This PR resolves [ONYX-1725] 
This PR fixes an issue related to active pill transition being shown. This was happening because we were relying on the animated value instead of the target value.
| iOS | Android |
|--------|--------|
| <Video src="https://github.com/user-attachments/assets/fc8e7228-54a5-4375-b6ac-3cd51d1623b5" /> | <Video src="https://github.com/user-attachments/assets/e4a918e9-907d-463e-b479-42f0c02523dc" /> | 
[ONYX-1725]: https://artsyproduct.atlassian.net/browse/ONYX-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: show only selected tab instead of tab transition

src/elements/Radio/RadioButton.tsx
Adds selected a11y state to radioButton to be used when testing with `@testing-library/react-native` and to improve the a11y of the radiobutton
=> feat: add selected a11y state to radioButton

ios/Podfile.lock, package.json, src/elements/Image/Image.tsx, src/setupJest.ts, yarn.lock
This PR exports `ImageSkeleton` to be used for image loaders.
Related PR: https://github.com/artsy/eigen/pull/12230
=> chore: export image skeleton

src/elements/Tabs/TabsWithHeader.tsx
This PR exposes a new prop to TabsWithHeader to allow us to use `TabsWithHeader` without the screen wrappers.
Initially I was thinking about only exporting the `Content` but because we have multiple props in common and we would want to use the `TabsWithHeader` most of the time, I avoided that. I am not strongly against it though
This will be used here https://github.com/artsy/eigen/pull/12370
=> chore: add hide screen to TabsWithHeader

src/elements/Tabs/TabMasonry.tsx
This PR resolves [PHIRE-2193] 
Fixes type-error with nullable refs on react 19, believe should be backwards compatible but will test before merging.
[PHIRE-2193]: https://artsyproduct.atlassian.net/browse/PHIRE-2193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: ref type for react 19

src/elements/Button/Button.tsx, src/elements/ButtonNew/Button.tsx, src/elements/Text/helpers.ts
This PR resolves [PHIRE-2350]
This PR fixes the broken text insde Palette's button.
This was recently raised in Energy and finally I had time to look into it. 
This was broken in previous releases of react-native, and the fix used to be to add the text line height. However since a few releases, this is no longer required and it's working fine on both platforms.
| Platform | Before | After |
|--------|--------|--------|
| Android | <img width="1080" height="2424" alt="Screenshot_1759319119" src="https://github.com/user-attachments/assets/48bfa62c-29f6-44c3-8bc2-652f4473cab9" /> | <img width="1080" height="2424" alt="Screenshot_1759319406" src="https://github.com/user-attachments/assets/07309b02-3add-45e9-bbc6-1c0ffe392cc7" /> |
| iOS | <img width="1206" height="2622" alt="Simulator …
=> fix: large button cropped

package.json, src/storybook/decorators.tsx, yarn.lock
Realised that palette-mobile wasn't running locally after my [expo bump PR](https://github.com/artsy/palette-mobile/pull/392) and the error was looking something like this:
Located the issue to be in jotai and I just refactored the storybook decorator to use useState instead of jotai and got rid of the dependency since we don't need another state manager :P
=> fix: remove jotai and refactor to use useState in order to fix palette-mobile
