lib/Theme.tsx
lib/atoms/Spacer/Spacer.stories.tsx
lib/atoms/Spacer/Spacer.tsx
lib/storybookHelpers.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.1.0--canary.9.3205259729.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@1.1.0--canary.9.3205259729.0
yarn add @artsy/palette-mobile@1.1.0--canary.9.3205259729.0
```
</details>

feat: deprecate ml mr mt mb on spacer, for x and y

---

.storybook/storybook.requires.js
lib/elements/Touchable/Touchable.stories.tsx
lib/elements/Touchable/Touchable.tsx

this is basically just pulling the changes from https://github.com/artsy/energy/pull/181.
<details>
<summary>📦 Published PR as canary version: <code>3.1.0--canary.25.3322700171.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@3.1.0--canary.25.3322700171.0
yarn add @artsy/palette-mobile@3.1.0--canary.25.3322700171.0
```
</details>

fix: touchable underlay color

---

lib/hooks.ts

just a bump
<details>
<summary>📦 Published PR as canary version: <code>6.0.0--canary.47.4078594480.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@6.0.0--canary.47.4078594480.0
yarn add @artsy/palette-mobile@6.0.0--canary.47.4078594480.0
```
</details>

chore: just a version bump

---

.storybook/storybook.requires.js
lib/elements/Button/Button.stories.tsx
lib/elements/Button/Button.tsx
src/App.tsx

margins etc were not working, now they are
<details>
<summary>📦 Published PR as canary version: <code>8.5.1--canary.55.4166766268.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@8.5.1--canary.55.4166766268.0
yarn add @artsy/palette-mobile@8.5.1--canary.55.4166766268.0
```
</details>

fix: button spacing

---

lib/elements/Button/Button.stories.tsx
lib/elements/Button/Button.tsx
lib/utils/MeasuredView.tsx

block was not working, and animations on colors were funky
<details>
<summary>📦 Published PR as canary version: <code>9.0.0--canary.60.4187667840.0</code></summary>
<br />
```bash
npm install @artsy/palette-mobile@9.0.0--canary.60.4187667840.0
yarn add @artsy/palette-mobile@9.0.0--canary.60.4187667840.0
```
</details>

fix: button block and animations

---

.husky/pre-commit
.husky/pre-push
package.json
yarn.lock

Adds our standard pre-commit lint/type checks. 

feat(toolchain): Add lint staged commit checks

---

lib/elements/Text/Text.stories.tsx
lib/elements/Text/Text.tsx

how nice! no more silly messages like https://artsy.slack.com/archives/C02BAQ5K7/p1676630778432989?thread_ts=1676630471.613259&cid=C02BAQ5K7

feat: OMG TYPES FOR STYLED COMPONENTS? FINALLY AND YES PLEASE!

---

src/elements/Avatar/Avatar.tsx
src/elements/Checkbox/Checkbox.tsx

Noticed some failing tests in https://github.com/artsy/eigen/pull/8468. This fixes those issues. 

fix(migration): fix missing migration items

---

src/elements/Checkbox/Checkbox.tsx
src/utils/hooks/useScreenDimensions.tsx

fix(checkbox): move from eigen

---

src/elements/LegacyScreen/LegacyScreen.tsx

Noticed that there were some API differences between Legacy screen component in Eigen and the one that was copied over here. We'll eventually be deleting this but in the meantime lets just copy the code over and point at palette-mobile in eigen so we can make the deletion process less error prone. 

fix(legacy-screen): use legacy screen code from Eigen

---

src/elements/Screen/Body.tsx
src/elements/Screen/BottomView.tsx
src/elements/Screen/FloatingHeader.tsx
src/elements/Screen/Header.tsx
src/elements/Screen/ScreenBase.tsx
src/elements/Screen/constants.ts
src/elements/Screen/index.tsx

Needing to do some wrangling to make this work between eigen and energy 😓

chore(screen): make stuff consistent

---

src/elements/Screen/Header.tsx
src/elements/Screen/ScreenBase.tsx

Oops! Need the Screen safe area for when stuff scrolls up. Of course of course.... 
Also perfectly centers the center area in the header.

fix(screen): fix safe area

---

src/elements/Screen/Header.tsx

Updates the title area to be more configurable, including animated titles

fix(header): make text more configurable

---

src/elements/Screen/Header.tsx

This PR resolves [MOPLAT-808](https://artsyproduct.atlassian.net/browse/MOPLAT-808)
[Slack context](https://artsy.slack.com/archives/C02NAJ2CGLW/p1686148782344189)
https://github.com/artsy/palette-mobile/assets/21178754/b5ac2a15-856e-4703-86fa-385c80c46538
[MOPLAT-808]: https://artsyproduct.atlassian.net/browse/MOPLAT-808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: adjust tab header animation

---

src/elements/Screen/FloatingHeader.tsx

Makes `<Header.FloatingHeader />` extend `FlexProps`

feat(screen): Make FloatingHeader more customizable

---

README.md

Small improvement to our setup instructions.

doc(setup): improve setup instructions

---

.storybook/storybook.requires.js
src/elements/Pill/Pill.stories.tsx
src/elements/Pill/Pill.tests.tsx
src/elements/Pill/Pill.tsx
src/elements/Pill/index.tsx

This PR adds the Pill element.
- Used Figma as the source of Truth
- Animations are still limited, only changing opacity when tapped but will add more complex animations to include the `active` state when pressed in a follow-up PR
Note: The video quality of the miniature is terrible, use fullscreen for details
https://github.com/artsy/palette-mobile/assets/15792853/766a4157-9708-4721-a511-27f8e06d0840

feat(Pill): Pill element

---

babel.config.js
ios/Podfile.lock
package.json
src/elements/ButtonNew/Button.tsx
src/elements/Pill/Pill.tsx
src/elements/ProgressBar/ProgressBar.tsx
src/elements/Screen/ScreenFlatList.tsx
src/elements/Screen/hooks/useAnimatedHeaderScrolling.tsx
src/elements/Screen/hooks/useListenForScreenScroll.tsx
src/elements/Skeleton/Skeleton.tsx
src/elements/Tabs/SubTabBar.tsx
src/elements/ToolTip/ToolTipFlyout.tsx
yarn.lock

This PR resolves [PHIRE-125] 
Update to reanimated 3, removed the worklets and tested out the app, will proceed with merging today possibly.
Linking also:
- original PR: https://github.com/artsy/palette-mobile/pull/125
- revert of original PR due to making it to eigen main before we were ready https://github.com/artsy/palette-mobile/pull/131
[PHIRE-125]: https://artsyproduct.atlassian.net/browse/PHIRE-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: bump reanimated 3

---

src/elements/Popover/Popover.tsx

Adds a background color to the popover element to show the users the screen is locked until they dismiss the popover.

feat(Popover): add background color

---

src/elements/Message/Message.tsx

This PR resolves [ONYX-295]
This PR adds support to icon positioning in the Message component.
[ONYX-295]: https://artsyproduct.atlassian.net/browse/ONYX-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: support icon positioning in Message component

---

README.md

Enhance  docs for  Developing Features using Local Versions of palette.

docs: update readme with Developing Features using Local Versions

---

src/elements/Tabs/TabMasonry.tsx

This PR adds support to injecting refs in the Masonry Flatlist

chore: support flatlist ref

---

src/elements/Pill/Pill.tsx

This PR follows design comment on updating the gray color on the dotted pill.

chore: update gray shade of dotted pill

---

.storybook/storybook.requires.js
src/elements/Banner/Banner.stories.tsx
src/elements/Banner/Banner.tsx

This PR updates the Banner component to follow the Artsy design system [figma link](https://www.figma.com/file/gZNkyqLT8AU3T61tluVJyB/Artsy-3.1-Design-System?type=design&node-id=6726-1797&mode=design&t=Y7MvmlATiELD11tQ-4) 🔒 and adds it to the storybook
As well as updating the API to match the one we have on [Palette](https://github.com/artsy/palette/blob/main/packages/palette/src/elements/Banner/Banner.tsx)
| iOS | Android |
|---|---|
| ![image](https://github.com/artsy/palette-mobile/assets/20655703/6c9502c8-8d14-499f-98f5-0270f28197da) | <img width="451" alt="image" src="https://github.com/artsy/palette-mobile/assets/20655703/962b8427-bc3b-40da-8e79-d217faa0e239"> |

feat: Update Banner Component

---

src/elements/Screen/index.tsx

This PR adds support for listening to scroll events emitted from the `Screen` component. By exporting this and hooking it to `ScrollView` based components, we can avoid nested scrollviews.

feat: support listening for screen events

---

src/elements/Screen/Header.tsx
src/elements/Tabs/TabsWithHeader.tsx

Makes it so that we can render jsx in the tabs title

feat(tabs): Update type to allow title to render jsx

---

.storybook/storybook.requires.js
src/elements/Switch/Switch.stories.tsx
src/elements/Switch/Switch.tsx
src/elements/Switch/index.tsx

This PR resolves part of [EMI-1715] 
This PR adds a Switch component to Palette Mobile 
| Android | iOS |
|---|---|
| <img width="452" alt="image" src="https://github.com/artsy/palette-mobile/assets/20655703/a46efd65-a2a1-4730-9d65-d60968e52d1d"> | <img width="430" alt="image" src="https://github.com/artsy/palette-mobile/assets/20655703/7f6df5e6-3dae-4651-a2fa-98985d27c0c7"> |
[EMI-1715]: https://artsyproduct.atlassian.net/browse/EMI-1715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add Switch component

---

src/elements/Switch/Switch.stories.tsx
src/elements/Switch/Switch.tsx

This PR updates the `onChange` prop in the switch component to follow the React Native implementation

fix: Update onChange prop in Switch

---

src/elements/Image/Image.tsx

**Make sure to enable palette-everywhere and show blurhash feature flags**
This PR solves https://www.notion.so/artsy/IT-looks-as-if-the-first-page-only-have-blur-hash-for-artist-images-366bdf8b2751449a943bb55fd0805d17?pvs=4
**What we have now:** Currently,  we have an Image component that is being covered by a skeleton. Once the image is done loading, we set the skeleton opacity to 0, and the image component shows up **from under it**. 
**Iusse:** If the UI thread and JS thread are both busy, we can end up having the skeleton opacity getting to 0, while the image (already loaded but not visible yet), has not be drawn yet. In this case, only the image box, which is black shows, and gives the impression there was no blurhash loaded. 
**Suggested change:**
The image component, is no longer …

fix: make sure image comes on top of the skeleton

---

package.json
yarn.lock

This PR fixes build issues on Palette
**Inspiration from:**
https://artsy.slack.com/archives/C02BAQ5K7/p1711387445231589?thread_ts=1711376030.650749&cid=C02BAQ5K7

chore: upgrade rn to latest minor version

---

src/elements/Button/FollowButton.tsx
src/elements/ButtonNew/Button.stories.tsx
src/elements/ButtonNew/FollowButton.tsx
src/utils/formatLargeNumber.ts
src/utils/formatLargeNumbers.tests.ts

This PR resolves [PHIRE-895] 
|Follow|Following|
|---|---|
|![follow](https://github.com/artsy/palette-mobile/assets/21178754/1d9029fe-a1cc-43c4-8805-6edaa63cba36)|![following](https://github.com/artsy/palette-mobile/assets/21178754/72867645-37df-4c7d-86b3-dc7b22fda5fb)|
[PHIRE-895]: https://artsyproduct.atlassian.net/browse/PHIRE-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: move follow button func to palette

---

src/elements/Screen/Body.tsx

This PR comes to address a potential prop leak introduced in the previous PR https://github.com/artsy/palette-mobile/pull/232

chore(Body): do not inject styles in Fragment component

---

package.json
yarn.lock

This PR updates @artsy/palette-tokens to the latest

chore: update @artsy/palette-tokens

---

src/elements/Screen/ScreenFlatList.tsx

This PR resolves [ONYX-1075] 
Follow-up on https://github.com/artsy/eigen/pull/10405/
https://github.com/artsy/palette-mobile/assets/11945712/03b42fec-c722-48e4-84be-fa112525f0a0
[ONYX-1075]: https://artsyproduct.atlassian.net/browse/ONYX-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: support innerRef inside Screen.Flatlist

---

package.json
yarn.lock

Bumps `react-native-collapsible-tab-view` to take advantage of the perf improvements that they did.

build(deps): bump collapsible-tab-view

---

tsconfig.app.json
tsconfig.json

remove tsappconfig and toggle noemit

chore: remove tsappconfig and toggle noemit

---

src/elements/Screen/StickySubHeader.tsx

Fix padding below sticky sub header

fix: sticky sub header padding

---

src/elements/Box/Box.stories.tsx
src/elements/Box/Box.tsx
src/elements/Chip/Chip.stories.tsx
src/elements/Radio/RadioButton.stories.tsx

Gap was introduced without the support of our spacings, this PR enables it.
https://github.com/user-attachments/assets/4e7cc4c4-3902-477b-9786-e2ac880780d1

feat(gap): use our spacing tokens with gap prop

---

src/elements/SearchInput/RoundSearchInput.tsx

This PR removes the layout animation from round search input.

chore: remove layout animation from round search input

---

src/elements/Button/Button.tsx

Reverts artsy/palette-mobile#288
I didn't really need this...

chore: revert "add button loading spinner testid"

---

src/elements/Checkbox/Check.tsx

Adds testID and accessibility to Check component

feat: add a11y to checkbox + testid

---

.tool-versions
ios/Podfile.lock
package.json
yarn.lock

This PR upgrades reanimated version to match Eigen's version here https://github.com/artsy/eigen/pull/11541

chore: upgrade reanimated version

---

src/tokens.ts

More Darkmode fixes on Folio
https://github.com/user-attachments/assets/b62b64ca-d9e0-4f3c-9b09-b766f2ed3d1e

chore: fix dark mode tokens

---

src/elements/Screen/Body.tsx
src/elements/Text/LinkText.tsx

This PR removes the force color props inside Body

chore: more dark mode fixes

---

src/elements/Popover/Popover.tsx

https://github.com/artsy/eigen/pull/11657#discussion_r1993172948
Add onOpenComplete callback to Popover.

feat: Add onOpenComplete callback to Popover

---

src/elements/Radio/RadioButton.stories.tsx
src/elements/Radio/RadioButton.tsx
src/elements/Radio/RadioDot.tsx

This PR adds the block variant to the radio button.

feat: add radio button block variant

---

scripts/flip-table-soft
src/elements/Radio/RadioButton.stories.tsx
src/elements/Radio/RadioButton.tsx

This makes sure that the radio button are full width

chore: fix issue with radio button

---

src/elements/Radio/RadioButton.tsx

update radio button text variant to match designs

chore: update radio button component

---

package.json
yarn.lock

Upgrade @artsy/palette-tokens to 6.5.0.

chore: Upgrade @artsy/palette-tokens to 6.5.0

---

src/elements/Pill/Pill.tsx

This PR fixes accessibility issues with the Pill.
|--------|--------|
| <img src="https://github.com/user-attachments/assets/3fb53d06-a869-496e-8312-9da2ec516736" /> | <img src="https://github.com/user-attachments/assets/1291f093-8d10-4308-b39c-0eea7966e572" /> |

chore: better accessibility for pills

---

ios/Podfile.lock
package.json
yarn.lock

Bumps safe-area-context to latest

build(deps): bump safe area view

---

package.json
src/setupJest.ts
yarn.lock

build(deps): react native testing lib to latest

---

.circleci/config.yml

update CircleCI orbs and Xcode version to match eigen

chore: update CircleCI orbs and Xcode version to match eigen

---

src/elements/Image/Image.tsx

This PR resolves [PHIRE-2133] 
On new arch/fabric using reanimated for a one off animation like opacity on load is much slower than using react natives animation lib directly. 
✅ ~~Do not merge until tested more but in theory should be fine on both old and new arch.~~ 
Admittedly not a very scientific test but the performance looks slightly better / comparable on the old arch with this change, can see in videos below after the change on home feed scrolling UI framerate stays above 45, after occasional drops to low 30s.
No video from new arch but it is pretty much unusable 🙃 
| Platform | Before | After |
|---|---|---|
| iOS | <video src="https://github.com/user-attachments/assets/91e6c114-7689-4282-9260-2eadfccdb332" width="400" /> | <video …

fix(perf): replace reanimated opacity animation with rn animated

---

package.json
yarn.lock

This PR resolves https://artsy.slack.com/archives/C02BAQ5K7/p1758812534519729
This PR aligns `FastImage` version on palette-mobile with eigen

chore: align fast image version on palette-mobile with eigen

---

src/elements/Skeleton/Skeleton.tsx

This PR fixes a regression we noticed in the new architecture, where components with images become too slow.
This fix should also help with the current infra

fix: performance issues on skeleton image

---

package.json
src/elements/Input/Input.tests.tsx
src/setupJest.ts
yarn.lock

This PR upgrades reanimated to 3.19.1
cc @brainbicycle

chore: upgrade reanimated to 3.19.1
